add: retry async function
idea2app/IRIS-Assessments-Crawler pull request #10
Opened 2023-10-13 02:50 UTC by PapayaHUANG

closes #9

2023-10-13 09:09 UTC, TechQuery requested changes

2023-10-13 09:09 UTC, TechQuery commented on src/index.tsx
> +}
```suggestion
async function retry<F extends (...data: any[]) => any>(executor: F, maxRetries = 1, interval = 0.5) {
  let lastError: Error | undefined;

  do {
    try {
      const data = executor();

      return (data instanceof Promise) ? await data : data;
    } catch (error) {
      lastError = error;
    }
    await sleep(interval):
  } while (--maxRetries);

  if (lastError) throw lastError;
}
```

2023-10-13 09:09 UTC, TechQuery commented on src/index.tsx
> +async function main(url, folder, concurrencyLimit?) {
参数类型要写好

2023-10-13 09:09 UTC, TechQuery commented on src/index.tsx
> +}
重试单个下载，否则过了几十分钟，其中一个炸了就要再来几十分钟……

2023-10-13 13:30 UTC, PapayaHUANG commented on src/index.tsx
> +}
斯国一！

2023-10-13 13:36 UTC, PapayaHUANG commented on src/index.tsx
> +}
所以是把重试的函数套在 `downloadHTML` 外面对吗？

2023-10-13 13:37 UTC, PapayaHUANG commented on src/index.tsx
> +}
重试的次数有没有什么约定俗成的规定啊？

2023-10-13 13:57 UTC, TechQuery commented on src/index.tsx
> +}
> 重试的次数有没有什么约定俗成的规定啊？

3次差不多了吧

2023-10-13 13:57 UTC, TechQuery commented on src/index.tsx
> +}
> 所以是把重试的函数套在 `downloadHTML` 外面对吗？

是的

2023-10-13 16:49 UTC, TechQuery requested changes

2023-10-13 16:49 UTC, TechQuery commented on src/index.tsx
> +  await retry(async () => await downloadHTML(url), maxRetries);
```suggestion
  await retry(() => downloadHTML(url), maxRetries);
```
（下同）

2023-10-14 11:36 UTC, TechQuery approved these changes

2023-10-14 11:37 UTC, merged